### ISSUE TITLE
请教几个问题

### ISSUE THREAD

**Issue by heng032000** [Seevil/cactus#12]
1.  存档页面用的模板是JS控制的么？请问内容要怎么修改？
2. CSS文件中有类似下面这样的写法
```
.ml2,.mx2{margin-left:1rem}
.mr2,.mx2{margin-right:1rem}
.mt2,.my2{margin-top:1rem}
.mb2,.my2{margin-bottom:1rem}
.m2{margin:1rem}
```
这样margin的四个方向单独写一行，有什么特殊用意么？

还有这种
```
.content .h2,.content h2,.content h3{font-size:1rem;font-weight:700;color:#eee}
.content .h2,.content h2{position:relative;text-transform:none;letter-spacing:normal
```
同一个属性也是分开写的。

谢谢

**Comment by Seevil** [comment]
1、归档页面 https://github.com/Seevil/cactus/blob/master/files.php 你看下就知道了
2、ml2 .mr2 .mt2 .mb2 你细细品我不太清楚
3、我是移植过来的没管那么多 ，只调整了一些大小位置有问题的地方，如果你觉得哪你有疑问直接改完看下有什么变化就好。

**Comment by heng032000** [comment]
明白了。谢谢！
