### ISSUE TITLE
Class 'App' not found

### ISSUE THREAD

**Issue by KangbaoShi** [Seevil/cactus#26]
创建文章，页面的时候提示。
'''
Class App not found.
'''
记得以前好像也遇到过。忘了咋填坑的。
![image](https://user-images.githubusercontent.com/34313868/109927894-cfd0bb80-7cff-11eb-81ef-ba97c6da4881.png)

**Comment by Seevil** [comment]
你这个是typecho的问题吧或者装了什么插件，这个主题没有注入文章发布的hook啥的

**Comment by KangbaoShi** [comment]
确实，启用了一个插件。。。。哈哈
