### ISSUE TITLE
Call to a member function Send() on null

### ISSUE THREAD

**Issue by Juskinbo** [Seevil/cactus#33]
在使用Cactus主题的时候，访问网站主页会显示`Call to a member function Send() on null`，在对index.php当中的today函数进行注释之后，网页才会恢复正常。

**Comment by Seevil** [comment]
php什么版本

**Comment by Juskinbo** [comment]
PHP 7.4.3

**Comment by Seevil** [comment]
我这边 php8.2  typecho1.2 测试正常。
