### ISSUE TITLE
首页每日一句的问题

### ISSUE THREAD

**Issue by scriptwang** [Seevil/cactus#9]
和这个问题一样 #5 ，我的环境是PHP5，有两个问题，
- 一个问题是获取每日一句失败
file_get_contents已打开，allow_url_fopen = On也已经打开，PHP报错信息
```
PHP message: PHP Warning:  file_get_contents(): Unable to find the wrapper &quot;compress.zlib&quot; - did you forget to enable it when you configured PHP? in /srv/usr/themes/cactus/functions.php on line 508
PHP message: PHP Warning:  file_get_contents(compress.zlib://https://rest.shanbay.com/api/v2/quote/quotes/today/): failed to open stream: No such file or directory in /srv/usr/themes/cactus/functions.php on line 508
```

这个报错打开该文件```/srv/usr/themes/cactus/functions.php```，找到508行，将
```
$json = file_get_contents("compress.zlib://".'https://rest.shanbay.com/api/v2/quote/quotes/today/');
```
改成
```
$json = file_get_contents('https://rest.shanbay.com/api/v2/quote/quotes/today/');
```
貌似是因为PHP5不支持compress.zlib的原因

- 第二个问题是前端没将json字符串转成对象

![image](https://user-images.githubusercontent.com/19930877/63632065-7398d000-c662-11e9-9e91-d8f5f8950d8c.png)
打开```/srv/usr/themes/cactus/footer.php```，找到片30行，添加一句
```
data = JSON.parse(data);
```
如图
![image](https://user-images.githubusercontent.com/19930877/63632088-da1dee00-c662-11e9-9483-9bf20715da0c.png)

然后就能正常显示了
![image](https://user-images.githubusercontent.com/19930877/63632101-00438e00-c663-11e9-8aed-ef3ff60098e4.png)

**Comment by Seevil** [comment]
compress.zlib报错 你看下你php的zlib组件 有没有启用？
然后菜鸡请教一下 json字符串转成对象 有什么作用哈？一脸懵逼代码复制的别人的。

**Comment by scriptwang** [comment]
> compress.zlib报错 你看下你php的zlib组件 有没有启用？
> 然后菜鸡请教一下 json字符串转成对象 有什么作用哈？一脸懵逼代码复制的别人的。

- compress.zlib
应该是我的compress.zlib没启用，对PHP不熟，报错的直接都删掉了/捂脸
-  json字符串转成对象
你看代码里面。如果不转对象的话，data.data是取不到东西的，是undefined，后面会报错
![image](https://user-images.githubusercontent.com/19930877/63696939-70face00-c84e-11e9-9b03-527edcbf5438.png)

**Comment by Seevil** [comment]
@scriptwang  哦哦，data.data取不到东西应该是你json 是空的或者不存在，因为我一直都是正常的哈
